### ISSUE TITLE
Adopt a charter

### ISSUE THREAD

**Issue by chrisdickinson** [iojs/readable-stream#105]
@iojs/streams 

There's work going on over [here](https://github.com/iojs/io.js/pull/599) to formalize the relationship between the TC and the WGs. One item that would be particularly useful is the concept of a charter.

Roughly speaking, this would delimit the scope of responsibilities of this WG, while also serving as a sort of "true north" for our decision-making. We've already touched on this issue a bit (see #99). While we each have our own ideas of how streams can and should evolve to better serve the needs of users, without a clearly stated goal these changes can be arbitrary, or may actually impede future improvements if we're not careful. Conversely, if we have a common goal, we can direct our efforts together to reach it.

We're working a bit backwards here owing to the fact that we're one of the first WGs, so whatever we decide here will ultimately have to be presented to and approved by the io.js TC.

Without further ado, here's a stab at a charter. Feel free to suggest edits or start from scratch:

-------------------

The Streams WG is dedicated to the support and improvement of the Streams API as used in io.js and the npm ecosystem. We seek to create a composable API that solves the problem of representing multiple occurrences of an event over time in a humane, low-overhead fashion. Improvements to the API will be driven by the needs of the ecosystem; interoperability and backwards compatibility with other solutions and prior versions are paramount in importance. Our responsibilities include:

* Addressing stream issues on the io.js issue tracker.
* Authoring and editing stream documentation within the io.js project.
* Reviewing changes to stream subclasses within the io.js project.
* Redirecting changes to streams from the io.js project to this project.
* Assisting in the implementation of stream providers within io.js.
* Recommending versions of readable-stream to be included in io.js.
* Messaging about the future of streams to give the community advance notice of changes.

**Comment by sonewman** [comment]
I think this a good idea and everything in the list seems reasonable.
It also does feel very agile like!
+1

**Comment by mikeal** [comment]
> Reviewing changes to stream subclasses within the io.js project.

Isn't the plan to vendor readable-stream?

**Comment by domenic** [comment]
Sure, but not vendor e.g. CryptoStream, so we should still review that code even though it's not in this repo.

**Comment by chrisdickinson** [comment]
This was merged into io.js!
