### ISSUE TITLE
.writable/.readable are not updated

### ISSUE THREAD

**Issue by mscdex** [iojs/readable-stream#123]
Yes I know that these are supposedly "legacy" properties, but setting them to `true` and never updating them is a bug IMHO.

How else are we supposed to know if any stream has ended/finished without peering into the private `_*ableState` properties? For example, if you have a function that takes in a Readable stream. If the stream has already ended, it's not like you can attach an `end` event handler or anything.

**Comment by isaacs** [comment]
I agree, if the fields are there, they may as well be updated when they change so that they're not lying.

Unless any others provide reasonable objections, patch welcome.

**Comment by mscdex** [comment]
PR is at iojs/io.js#1217
